<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sessions Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #f48545; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #2d2d2d; font-size: 24px; }
        .header h1 span { color: #f48545; }
        .header p { margin: 5px 0 0; color: #777; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #f9fafb; font-weight: bold; color: #555; }
        .status-Completed { color: #10b981; font-weight: bold; }
        .status-assigned { color: #f59e0b; font-weight: bold; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
        .meta-info { margin-bottom: 15px; }
        .meta-info p { margin: 2px 0; font-size: 11px; color: #555; }
    </style>
</head>
<body>
    <div class="header">
        <h1>STU<span>SION</span></h1>
        <p>Counseling Session System</p>
    </div>

    <div class="meta-info">
        <p><strong>Report Type:</strong> {{ $reportType ?? 'General' }} Sessions Report</p>
        <p><strong>Generated By:</strong> {{ $generatedBy }}</p>
        <p><strong>Date Generated:</strong> {{ now()->format('F j, Y, g:i A') }}</p>
        <p><strong>Total Sessions:</strong> {{ $sessions->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Student Name</th>
                <th>Counselor</th>
                <th>Session Type</th>
                <th>Date & Time</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sessions as $session)
            <tr>
                <td>{{ $session->student->name ?? 'Unknown' }}</td>
                <td>{{ $session->counselor->name ?? 'Unknown' }}</td>
                <td>{{ $session->type }}</td>
                <td>{{ \Carbon\Carbon::parse($session->date)->format('M d, Y') }} at {{ \Carbon\Carbon::parse($session->time)->format('g:i A') }}</td>
                <td class="status-{{ $session->status }}">{{ ucfirst($session->status) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Report generated by: {{ $generatedBy }} on {{ now()->format('Y-m-d H:i:s') }}
    </div>
</body>
</html>
